### ISSUE TITLE
Passing multiple providers to a module invocation

### ISSUE THREAD

**Issue by vincenthsh** [chanzuckerberg/fogg#734]
I'm able to define additional_providers for the AWS  provider:

```yaml
# omitting defaults with default aws provider config
envs:
  my-env:
    providers:
      aws:
        additional_providers:
          replica:
            region: us-east-2
```

which generates `fogg.tf` with 2 providers (`aws` and `aws.replica`)

but the module I'm trying to use still complains I need to explicitly pass them in:

```hcl
module "foo" {
  source = "..."

  providers = {
    aws         = aws
    aws.replica = aws.replica
  }
}
```

I believe this is currently not supported in the tf module invocation templates? 

I'm ok to create a PR for this, but I'm wondering if I'm missing something on the TF config side?
